resource_group_name           = "my-resource-group"
location                      = "East US"
storage_account_name          = "mystorageaccount"
storage_container_name        = "mycontainer"
storage_account_tier          = "Standard"
storage_account_replication_type = "LRS"